/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      fontFamily: {
        display: ['"Fraunces Variable"', 'Georgia', 'serif'],
        sans: ['"Inter Variable"', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono Variable"', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'display-xl': ['clamp(2.25rem, 4vw + 1rem, 3.5rem)', { lineHeight: '1.05' }],
        h1: ['2rem', { lineHeight: '1.15' }],
        h2: ['1.5rem', { lineHeight: '1.2' }],
        h3: ['1.125rem', { lineHeight: '1.3' }],
        body: ['0.9375rem', { lineHeight: '1.6' }],
        caption: ['0.8125rem', { lineHeight: '1.5' }],
        micro: ['0.6875rem', { lineHeight: '1.4', letterSpacing: '0.08em' }],
      },
      colors: {
        canvas: 'rgb(var(--canvas) / <alpha-value>)',
        'zen-canvas': 'rgb(var(--zen-canvas) / <alpha-value>)',
        surface: 'rgb(var(--surface) / <alpha-value>)',
        sunken: 'rgb(var(--sunken) / <alpha-value>)',
        line: 'rgb(var(--line) / <alpha-value>)',
        'line-strong': 'rgb(var(--line-strong) / <alpha-value>)',
        ink: 'rgb(var(--ink) / <alpha-value>)',
        'ink-muted': 'rgb(var(--ink-muted) / <alpha-value>)',
        'ink-faint': 'rgb(var(--ink-faint) / <alpha-value>)',
        accent: 'rgb(var(--accent) / <alpha-value>)',
        'accent-hover': 'rgb(var(--accent-hover) / <alpha-value>)',
        'accent-strong': 'rgb(var(--accent-strong) / <alpha-value>)',
        'accent-soft': 'rgb(var(--accent-soft) / <alpha-value>)',
        'state-compare': 'rgb(var(--state-compare) / <alpha-value>)',
        'state-compare-text': 'rgb(var(--state-compare-text) / <alpha-value>)',
        'state-compare-ring': 'rgb(var(--state-compare-ring) / <alpha-value>)',
        'state-swap': 'rgb(var(--state-swap) / <alpha-value>)',
        'state-swap-text': 'rgb(var(--state-swap-text) / <alpha-value>)',
        'state-swap-ring': 'rgb(var(--state-swap-ring) / <alpha-value>)',
        'state-sorted': 'rgb(var(--state-sorted) / <alpha-value>)',
        'state-sorted-text': 'rgb(var(--state-sorted-text) / <alpha-value>)',
        'state-sorted-ring': 'rgb(var(--state-sorted-ring) / <alpha-value>)',
        'state-pivot': 'rgb(var(--state-pivot) / <alpha-value>)',
        'state-pivot-text': 'rgb(var(--state-pivot-text) / <alpha-value>)',
        'state-pivot-ring': 'rgb(var(--state-pivot-ring) / <alpha-value>)',
      },
      borderRadius: {
        sm: '8px',
        md: '12px',
        lg: '16px',
        pill: '9999px',
      },
      boxShadow: {
        e1: '0 1px 2px rgb(15 23 42 / .04)',
        e2: '0 4px 12px -2px rgb(15 23 42 / .08)',
        e3: '0 16px 40px -12px rgb(15 23 42 / .18)',
      },
      transitionTimingFunction: {
        'ease-out-custom': 'var(--ease-out)',
      },
      transitionDuration: {
        fast: '120ms',
        base: '200ms',
        slow: '320ms',
      },
    },
  },
  plugins: [],
}
